[package]
name = "glide"     # becomes the import name by default
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
git2 = "0.20.2"

[dependencies.pyo3]
version = "0.18"
features = ["extension-module"]

[package.metadata.maturin]
bindings = "pyo3"
